name: Vercel Auto Deployment Check

on:
  push:
    branches: ["main"]

jobs:
  check-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verifikasi Status Aplikasi
        run: echo "Aplikasi warga berhasil terhubung secara otomatis dan aman dengan Vercel!"
